CREATE TABLE sentiments_table(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);