CREATE TABLE user_comments(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name TEXT UNIQUE NOT NULL,
    last_name TEXT UNIQUE NOT NULL,
    feedback TEXT NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    product_type TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);